name: danny
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.7
  background_fetch: ^1.1.5
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.5
  connectivity_plus: ^3.0.3
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  firebase_storage: ^11.0.16
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_reactive_ble:
    git:
        url: https://github.com/Sockitos/flutter_reactive_ble
        path: packages/flutter_reactive_ble
  freezed_annotation: ^2.2.0
  image_picker: ^0.8.7
  intl: ^0.17.0
  json_annotation: ^4.8.0
  page_transition: ^2.0.9
  path_provider: ^2.0.14
  pdf: ^3.9.0
  pdfx: ^2.3.0
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  screenshot: ^1.3.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.20
  smooth_page_indicator: ^1.0.1
  syncfusion_flutter_charts: ^21.1.35
  table_calendar: ^3.0.8
  uuid: ^3.0.7

dependency_overrides:
  reactive_ble_mobile:
    git:
        url: https://github.com/Sockitos/flutter_reactive_ble
        path: packages/reactive_ble_mobile
  reactive_ble_platform_interface:
    git:
        url: https://github.com/Sockitos/flutter_reactive_ble
        path: packages/reactive_ble_platform_interface

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen: ^5.2.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/danny.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 700
