// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6HObImDhFlD-Ngt2zIm-T_kIe7T6xaiU',
    appId: '1:735469417489:web:3ae7b21df955ac56d56db0',
    messagingSenderId: '735469417489',
    projectId: 'dan-ist',
    authDomain: 'dan-ist.firebaseapp.com',
    databaseURL: 'https://dan-ist.firebaseio.com',
    storageBucket: 'dan-ist.appspot.com',
    measurementId: 'G-Z15F1YQPRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALdtjL-bbafrGos_UVz29avrwhv8DEvAs',
    appId: '1:735469417489:android:854f35f677c1759cd56db0',
    messagingSenderId: '735469417489',
    projectId: 'dan-ist',
    databaseURL: 'https://dan-ist.firebaseio.com',
    storageBucket: 'dan-ist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXUorTBR6SwwUy9rLSwMxcZRdd4ScgNvg',
    appId: '1:735469417489:ios:b171d5c47fb6af9cd56db0',
    messagingSenderId: '735469417489',
    projectId: 'dan-ist',
    databaseURL: 'https://dan-ist.firebaseio.com',
    storageBucket: 'dan-ist.appspot.com',
    androidClientId:
        '735469417489-7kgt77djl324elt9fj7eh7i5tgqn8p4o.apps.googleusercontent.com',
    iosClientId:
        '735469417489-bo6qtc19o87l3sc3unv248rrkmgcjc88.apps.googleusercontent.com',
    iosBundleId: 'com.example.danny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXUorTBR6SwwUy9rLSwMxcZRdd4ScgNvg',
    appId: '1:735469417489:ios:b171d5c47fb6af9cd56db0',
    messagingSenderId: '735469417489',
    projectId: 'dan-ist',
    databaseURL: 'https://dan-ist.firebaseio.com',
    storageBucket: 'dan-ist.appspot.com',
    androidClientId:
        '735469417489-7kgt77djl324elt9fj7eh7i5tgqn8p4o.apps.googleusercontent.com',
    iosClientId:
        '735469417489-bo6qtc19o87l3sc3unv248rrkmgcjc88.apps.googleusercontent.com',
    iosBundleId: 'com.example.danny',
  );
}
